name: frame-ql Python CI

on:
  push:
    branches: [ "main" ] # Runs on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Runs on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The type of machine to run the job on
    strategy:
      matrix:
        python-version: ["3.9"] # Test against multiple Python versions

    steps:
      # 1. Checks out your repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Sets up the specified version of Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      # 3. Use the dedicated action to install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # 4. Install poetry and run the tests using pytest
      - name: Install dependencies
        run: poetry install

      - name: Run tests with pytest
        run: poetry run pytest
